# A example scrape configuration for running Prometheus with
# Linode.

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Discover Node Exporter instances to scrape.
  - job_name: "node"
    linode_sd_configs:
      - authorization:
          credentials: "<api_token from linode account>"
    relabel_configs:
      # Only scrape targets that have a tag 'monitoring'.
      - source_labels: [__meta_linode_tags]
        regex: ".*,monitoring,.*"
        action: keep

      # Use the public IPv6 address and port 9100 to scrape the target.
      - source_labels: [__meta_linode_public_ipv4]
        target_label: __address__
        replacement: "[$1]:9100"

# Define alerting rules
rule_files:
  - "custom.rules"  # Name of the file containing alerting rules

# Define Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]  # Alertmanager's target address
